version: "3.3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=nekidaem_test
      - POSTGRES_USER=nekidaem_test
      - POSTGRES_PASSWORD=nekidaem_test
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/nekidaem_test
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
