# Generated by Django 3.0.7 on 2020-06-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200610_0448'),
        ('users', '0002_auto_20200611_0138'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfeedseen',
            unique_together={('user', 'post')},
        ),
    ]
